apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: "go-storage:latest"
          imagePullPolicy: Never
          env:
            - name: AMQP_URL
              value: "amqp://{{ .Values.global.rabbitmq.username }}:{{ .Values.global.rabbitmq.password }}@rabbitmq.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.rabbitmq.service.port }}/{{ .Values.global.rabbitmq.vhost | default "/" }}"
            - name: DATABASE_URL
              value: "postgres://{{ .Values.global.postgresql.username }}:{{ .Values.global.postgresql.password }}@postgresql.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.postgresql.service.port }}/{{ .Values.global.postgresql.database}}"
