global:
  postgresql:
    image: "postgres:13"
    username: "admin"
    password: "${POSTGRES_PASSWORD}"
    database: "mydb"
    service:
      port: 5432

  rabbitmq:
    image: "rabbitmq:3-management"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    service:
      port: 5672
      managementPort: 15672
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - host: rabbitmq.local
          paths:
            - path: /
              pathType: Prefix
      tls: []
service1:
  replicas: 1
# service2:
#   image: myservice2:latest
#   replicas: 2
#   service:
#     port: 8082

# service3:
#   image: myservice3:latest
#   replicas: 1
#   service:
#     port: 8081
