global:
  postgresql:
    image: "postgres:latest"
    username: "admin"
    password: "${POSTGRES_PASSWORD}"
    database: "mydb"
    service:
      port: 5432

  rabbitmq:
    image: "rabbitmq:3-management"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    service:
      port: 5672
      managementPort: 15672
    ingress:
      enabled: true
      annotations: {}
      hosts:
        - host: rabbitmq.local
          paths:
            - path: /
              pathType: Prefix
      tls: []
