apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.global.rabbitmq.image }}"
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.global.rabbitmq.username }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.global.rabbitmq.password }}"
          ports:
            - containerPort: {{ .Values.global.rabbitmq.service.port }}
            - containerPort: {{ .Values.global.rabbitmq.service.managementPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: connection-port
      port: {{ .Values.global.rabbitmq.service.port }}
      targetPort: {{ .Values.global.rabbitmq.service.port }}
    - name: management-port
      port: {{ .Values.global.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.global.rabbitmq.service.managementPort }}
  selector:
    app: rabbitmq
---

{{- if .Values.global.rabbitmq.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  annotations:
    {{- range $key, $value := .Values.global.rabbitmq.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.global.rabbitmq.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: rabbitmq
                port:
                  number: {{ $.Values.global.rabbitmq.service.managementPort }}
          {{- end }}
    {{- end }}
  {{- if .Values.global.rabbitmq.ingress.tls }}
  tls:
    {{- range .Values.global.rabbitmq.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
